### ISSUE TITLE
Member Image

### ISSUE THREAD

**Issue by wuqinghao0102** [scalableinternetservices/goda#4]
![img_1743](https://cloud.githubusercontent.com/assets/8999618/10401856/9111f406-6e76-11e5-99c2-998a99d03628.JPG)

**Comment by zhiangli** [comment]
![dsc_1058](https://cloud.githubusercontent.com/assets/9508990/10402023/9bbe97be-6e77-11e5-9ce8-b48020183ad6.JPG)

**Comment by elaine127** [comment]
![self](https://cloud.githubusercontent.com/assets/12179911/10402063/db5193a4-6e77-11e5-8d28-eb22dda48430.jpg)

**Comment by xinliu-UCSB** [comment]
![xin](https://cloud.githubusercontent.com/assets/14937101/10402128/53367286-6e78-11e5-9d54-81f2e49bc935.JPG)

**Comment by zhiangli** [comment]
![20151009_182417000_ios](https://cloud.githubusercontent.com/assets/9508990/10402194/b504ef92-6e78-11e5-8040-f2b32c272f8f.jpg)
